name: Generate Snake Animation

on:
  # Run automatically every day at midnight
  schedule:
    - cron: "0 0 * * *"
  # Run manually from the Actions tab
  workflow_dispatch:
  # Run automatically when pushing to the repository
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Generate Snake SVG
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg

      - name: Commit and Push the generated SVG
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Generated snake animation" || exit 0
          git push
